server:
  port: 8090

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ht?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
  http:
    encoding:
      force: true
mybatis:
  type-aliases-package: cn.tedu.pojo
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mappers/*.xml





